Feature/implement user microservice
LoneXDii/OnlineShop pull request #1
Opened 2024-11-11 07:52 UTC by LoneXDii

2024-11-15 09:37 UTC, MefistoSamael requested changes

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Domain/Exceptions/ApiException.cs
move all exceptions to application

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.API/Middleware/ExceptionsMiddleware.cs
> +		};
why don't you use ProblemDetails?

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/EmailConfirmationUseCase/EmailConfirmationRequestHandler.cs
> +		var code = HttpUtility.UrlDecode(request.code);
Application layer have to know nothing about fact that you are using web. It is better to remove this from application layer

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/LoginUserUseCase/LoginUserRequestHandler.cs
> +			throw new LoginException("Incorrect email or password");
use badRequest instead

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/LoginUserUseCase/LoginUserRequestHandler.cs
> +			throw new LoginException("Email is not verified");
use badRequest

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UserService.Application.csproj
dependency rule violated. Application layer have to not know about infrastructure

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/RegisterUserUseCase/RegisterUserRequestHandler.cs
> +			var imageUrl = $"http://127.0.0.1:10000/devstoreaccount1/avatars/{imageId}";
don't configure url here. Do it in blobService

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/RegisterUserUseCase/RegisterUserRequestHandler.cs
> +			throw new RegisterException($"Cannot register user: {errors}");
use badRequest

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/RegisterUserUseCase/RegisterUserRequestHandler.cs
> +			var confirmationLink = $"https://localhost:7001/api/account/confirm/email={email}&code={code}";
this shouldn't be located in application

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/AuthUseCases/RegisterUserUseCase/RegisterUserRequestHandler.cs
> +			await emailService.SendEmailConfirmationCodeAsync(user.Email, confirmationLink);
all await statements should be followed and preceeded by blank lines

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/GetUserInfoUseCase/GetUserInfoRequestHandler.cs
> +        return userDTO;
return statement should be preceeded by blank line

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/GetUserInfoUseCase/GetUserInfoRequestHandler.cs
> +        }
conditional statements should be followed and preceded by blank line. Fix tabulation

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/ListUsersWithPaginationUseCase/ListUsersWithPaginationRequestHandler.cs
> +			throw new NotFoundException("No such page");
fix tabulation

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/ListUsersWithPaginationUseCase/ListUsersWithPaginationRequestHandler.cs
> +		var totalPages = (int)Math.Ceiling(count / (double)request.pageSize);
use validators to check input values

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/UpdateEmailUseCase/UpdateEmailRequestHandler.cs
> +		}
move this to validator

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/UpdateEmailUseCase/UpdateEmailRequestHandler.cs
> +		var confirmationLink = $"https://localhost:7001/api/account/confirm/email={email}&code={code}";
this shouldn't be located in application layer

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/UseCases/UserUseCases/UpdateUserUseCase/UpdateUserRequestHandler.cs
> +			var imageUrl = $"http://127.0.0.1:10000/devstoreaccount1/avatars/{imageId}";
this shouldn't be located in application

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Application/Mapping/AppMappingProfile.cs
> +		CreateMap<UpdateUserDTO, AppUser>();
separate mappings into different files

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Infrastructure/Database/DbInitializer/DbInitializer.cs
> +	}
use hasData methods

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Infrastructure/Services/Authentication/ITokenService.cs
> +	Task<string> GetRefreshTokenAsync(AppUser user);
fix tabulation

2024-11-15 09:37 UTC, MefistoSamael commented on UserService/UserService.Infrastructure/Services/Authentication/TokenService.cs
> +    {
fix tabulation

2024-11-15 14:00 UTC, LoneXDii commented on UserService/UserService.Application/UserService.Application.csproj
Discussed

2024-11-22 12:16 UTC, MefistoSamael approved these changes

2024-11-22 17:30 UTC, merged